api:                        # The application api configuration
  address: "localhost:3000" # The application listen address
  user:                     # The application user, it will be persisted on the application startup
    login: admin            # The application user login, in a production environment this must be secured
    password: admin         # The application user password, in a production environment this must be secured

database:                                                                                         # The application database configurations
  provider: "sqlite"                                                                            # The database provider (postgres, sqlite)
  # provider: "postgres"                                                                            # The database provider (postgres, sqlite)
  # dsn: "postgresql://api-gatekeeper:api-gatekeeper@localhost:5432/api-gatekeeper?sslmode=disable" # The database connection dsn
  dsn: "gatekeeper.db" # The database connection dsn

backends:                         # The backends configurations
  - name: "ping-backend"          # The backend name
    host: "http://localhost:8080" # The backend host
    scopes:                       # (Optional) The authentication scopes required for every route in this backend
      - "ping-backend-scope"
    headers: # (Optional) The headers to be included in the request for every route in this backend
      Authorization: "Bearer foobar"
      X-Example-Header-backend: "example backend header"
    routes:                     # The backend routes
      - method: "GET"           # The route method
        backendPath: "/ping"    # The absolute path on your application, path variables are replicated as long as both have the same name
        gatekeeperPath: "/ping" # The absolute path that will be exposed by the api-gatekeeper, path variables are replicated as long as both have the same name
        timeoutSeconds: 30      # (Optional) The timeout in seconds, set to 0 to dont timeout
        isPublic: false         # (Optional) If this route is public
        scopes:                 # (Optional) The authentication scopes required for this route, they will be added with the backend scopes
          - "ping-backend.get-ping-scope"
        headers: # (Optional) The headers to be included in the request for this route
          X-Example-Header-Route: "example route header"
