services:
  postgres:
    image: postgres:16.3-alpine
    container_name: api-gatekeeper-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: api-gatekeeper
      POSTGRES_PASSWORD: api-gatekeeper
      POSTGRES_DB: api-gatekeeper
