@host = http://localhost:3000
@basicToken = YWRtaW46YWRtaW4=

@userId = {{CreateUser.response.body.id}}

# @name LoginJWT
POST {{host}}/api-gatekeeper/v1/users/login
Content-Type: application/json
Authorization: Basic {{basicToken}}
X-Token-Type: jwt
###

# @name CreateUser
POST {{host}}/api-gatekeeper/v1/users
Content-Type: application/json
Authorization: Basic {{basicToken}}

{
  "login": "example-login",
  "password": "example-password",
  "properties": {
    "example-property-key-1": "example-property-value-1",
    "example-property-key-2": "example-property-value-2",
    "example-property-key-3": "example-property-value-3"
  },
  "scopes": [
    "example-scope-1",
    "example-scope-2",
    "example-scope-3"
  ]
}
###

# @name UpdateUser
PUT {{host}}/api-gatekeeper/v1/users/{{userId}}
Content-Type: application/json
Authorization: Basic {{basicToken}}

{
  "login": "example-login-new",
  "password": "example-password",
  "properties": {
    "example-property-key-1": "example-property-value-1",
    "example-property-key-2": "example-property-value-2",
    "example-property-key-3": "example-property-value-3",
    "example-property-key-4": "example-property-value-4"
  },
  "scopes": [
    "example-scope-1",
    "example-scope-2",
    "example-scope-3",
    "example-scope-4"
  ]
}
###

# @name DeleteUser
DELETE {{host}}/api-gatekeeper/v1/users/{{userId}}
Content-Type: application/json
Authorization: Basic {{basicToken}}
###

# @name GetAllUsers
GET {{host}}/api-gatekeeper/v1/users
Content-Type: application/json
Authorization: Basic {{basicToken}}
###

# @name GetUserByID
GET {{host}}/api-gatekeeper/v1/users/{{userId}}
Content-Type: application/json
Authorization: Basic {{basicToken}}
###
